apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: workshops.operator.redhatgov.io
spec:
  group: operator.redhatgov.io
  names:
    kind: Workshop
    listKind: WorkshopList
    plural: workshops
    singular: workshop
  scope: Namespaced
  kind: NumberOfStudents
  kind: workshopName
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  additionalPrinterColumns:
  - name: Workshop
    type: string
    description: Associated student workshop
    JSONPath: .spec.workshopName
