apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: students.operator.redhatgov.io
spec:
  group: operator.redhatgov.io
  names:
    kind: Student
    listKind: StudentList
    plural: students
    singular: student
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
