apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: workshop-operator
  template:
    metadata:
      labels:
        name: workshop-operator
    spec:
      serviceAccountName: workshop-operator
      containers:
        - name: workshop-operator
          # Replace this with the built image name
          image: "quay.io/jduncan/workshop-operator:latest"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "workshop-operator"
